name: "NuGet Package"

on:
  release:
    types: [published]
  workflow_dispatch:
  

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: "0"
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Pack
      run: |
        dotnet pack ./Jinaga/ -c Release -o ./packages
        dotnet pack ./Jinaga.UnitTest/ -c Release -o ./packages
        dotnet pack ./Jinaga.Graphviz/ -c Release -o ./packages
        dotnet pack ./Jinaga.Store.SQLite/ -c Release -o ./packages
        dotnet pack ./Jinaga.Maui/ -c Release -o ./packages
    - name: Publish Nuget to GitHub registry
      run: dotnet nuget push ./packages/*.nupkg -k ${{secrets.NUGET_API_KEY}} -s https://api.nuget.org/v3/index.json --skip-duplicate --no-symbols
